Estimate tps and not hard-code it
Steveplays28/realisticsleep pull request #76
Opened 2024-10-08 09:39 UTC by themg95

Fixes #7

2024-10-08 11:35 UTC, Steveplays28 commented
Thanks for the PR themg95!
I'll merge and release it when I have time.

2024-10-08 14:46 UTC, Steveplays28 commented
Looks good! I suggested a couple of changes in the review comments, would appreciate those changes if you have time.

I'll likely split up this tick mixin in the future for improved code quality.

2025-01-03 13:26 UTC, Steveplays28 requested changes

2025-01-03 13:26 UTC, Steveplays28 commented on common/src/main/java/io/github/steveplays28/stevesrealisticsleep/mixin/ServerWorldMixin.java
> +			System.out.println(stevesrealisticsleep$estimatedTps);
This `System.out#println` call shouldn't be here

2025-01-03 13:26 UTC, Steveplays28 commented on common/src/main/java/io/github/steveplays28/stevesrealisticsleep/mixin/ServerWorldMixin.java
> +	private int stevesrealisticsleep$ticksSinceLastChecked = 0;
Could be more descriptive, e.x.:
```suggestion
	private int stevesrealisticsleep$ticksSinceLastTpsCheck = 0;
```

2025-01-03 13:27 UTC, Steveplays28 commented
I just realized I never actually submitted my pending review comments, sorry about that!
I'll make the changes and get this merged.

2025-01-04 09:16 UTC, themg95 commented on common/src/main/java/io/github/steveplays28/stevesrealisticsleep/mixin/ServerWorldMixin.java
> +			System.out.println(stevesrealisticsleep$estimatedTps);
oops accidentally left some debug stuff :smile:

2026-07-22 12:37 UTC, Steveplays28 commented
Thanks for your PR @themg95! I've merged it manually.
I'm temporarily back from my break from modding.

2026-07-22 12:37 UTC, closed without merging